### PR TITLE
Move to puppet 4

### PR DESCRIPTION
**Pull request by ekohl**
Includes a modulesync and https://github.com/Katello/puppet-katello/pull/188 with some type fixes.

### CODE REVIEW

**Comment by ekohl** [comment]
There is no newer puppet-foreman version out so I think it's weird to increase it.

**Comment by stbenjam** [comment]
I guess, but does this work with the latest released version on the Forge? Tests would be pulling out of git which is 8.0, I feel like the requirements should match what we're testing against

**Comment by ekohl** [comment]
You're right that the version in metadata.json is already 8.0.0. Given we hardly call anything from the foreman module (just ```foreman::config::passenger::fragment``` and some resource ordering) I think it's safe to bump the requirement because those are unlikely to change.

**Comment by ekohl** [comment]
I've added 3 additional commits, 2 are cleanups I think are safe.

**Comment by ekohl** [comment]
I forgot that there are more entry classes, like admin and crane. Fixing those as well.

**Comment by ekohl** [comment]
@stbenjam can you re-review?

**Comment by ekohl** [comment]
Merged without the stdlib commit because I trust it'll become stable again and shouldn't impact releases.

**Pull request closed without merging**
