### PR TITLE
Optimize tests

### PR DESCRIPTION
**Pull request by ekohl**
By using on_supported_os we can benefit from ONLY_OS thus reducing our test runtime. The use of verify_exact_contents makes it slightly easier to read.

### CODE REVIEW

**Comment by ekohl** [comment]
It looks like the difference is negligible since we only support RH7, C7 and SL7 but ONLY_OS is set to RH7 and SL7.

**Comment by ehelms** [comment]
@ekohl did you still want this merged?

**Comment by ekohl** [comment]
@ehelms yes

**Comment by ekohl** [comment]
I rebased this and when the tests are green I intend to merge this.

**Pull request merged**
