### PR TITLE
fixes #13451 - enables squid management in pulp

### PR DESCRIPTION
**Pull request by daviddavis**
Updating https://github.com/Katello/puppet-katello/pull/109

### CODE REVIEW

**Comment by stbenjam** [comment]
To get tests to pass, I guess we need the squid3 fixture here too

**Comment by stbenjam** [comment]
Otherwise :+1:

**Comment by stbenjam** [comment]
ACK, thanks, sorry for being a pain :grin:

**Comment by daviddavis** [comment]
No worries. columbus_bluejackets svg

Should be good now.

**Pull request merged**
