### PR TITLE
Adding support for Scientific Linux

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks good, but I can't tell if the test failures are caused by this or something unrelated.

**Comment by ehelms** [comment]
Local testing, this appears to be failing because its not getting the apache_version properly. I am still trying to figure out how to get it to grab it properly.

**Comment by ehelms** [comment]
Updated. I was calling the version class and not referencing the variable itself.

**Comment by ekohl** [comment]
:+1:

**Comment by ehelms** [comment]
@stbenjam mind taking a peek as well?

**Comment by stbenjam** [comment]
Looks good to me ACK

**Pull request merged**
