### PR TITLE
enable repo auth for pulp

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Note:  I would hold off on merging this until https://pulp.plan.io/issues/1667 is resolved

**Comment by ehelms** [comment]
Starting to think about merging puppet-katello_devel or moving the pulp and candlepin configurations into a re-usable class..... please to update https://github.com/Katello/puppet-katello_devel/blob/master/manifests/init.pp

**Comment by jlsherrill** [comment]
@ehelms agreed, opened https://github.com/Katello/puppet-katello_devel/pull/60

**Comment by ehelms** [comment]
ACK

**Pull request merged**
