### PR TITLE
Modulesync update

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
`$use_passenger` can be removed from init.pp, not used and causing errors on puppet 4 strict_variables as it's not defined in params.pp.

**Comment by ekohl** [comment]
> $use_passenger can be removed from init.pp, not used and causing errors on puppet 4 strict_variables as it's not defined in params.pp.

Added that to https://github.com/Katello/puppet-katello/pull/140

**Comment by ehelms** [comment]
PR part passing

**Comment by ekohl** [comment]
ACK

**Pull request merged**
