### PR TITLE
Refs #14858 - removes gutterball

### PR DESCRIPTION
**Pull request by cfouant**
Main PR: https://github.com/Katello/katello-packaging/pull/213

### CODE REVIEW

**Comment by stbenjam** [comment]
Missing one:
  ./templates/plugin/gutterball/gutterball.yaml.erb

**Comment by stbenjam** [comment]
Nitpick, no BZ's in upstream commit messages

**Comment by cfouant** [comment]
Good eye, thanks @stbenjam

**Comment by ekohl** [comment]
ACK

**Comment by stbenjam** [comment]
Please don't merge any of these yet until we try them together to make sure it works, but from a puppet perspective it is good :)

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
