### PR TITLE
Fixes #10885 - Allow customizing mongodb path

### PR DESCRIPTION
**Pull request by adamruzicka**
~~Requires https://github.com/Katello/puppet-katello/pull/72~~
Requires https://github.com/Katello/puppet-pulp/pull/72

### CODE REVIEW

**Comment by ekohl** [comment]
After https://github.com/Katello/puppet-pulp/pull/72 is merged, :+1:

**Comment by stbenjam** [comment]
[test]

**Comment by stbenjam** [comment]
Need https://github.com/Katello/puppet-pulp/pull/84 before merging, so it ends up in the installer correctly

**Comment by stbenjam** [comment]
Was already done.

**Comment by stbenjam** [comment]
Thanks @adamruzicka

**Pull request merged**
