### PR TITLE
refs #15217 - puppet 4 support

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like all variables in ```katello.yaml.erb``` aren't in scope.

**Comment by ekohl** [comment]
The other Katello modules use ```scope[]```, isn't that the modern way rather than ```scope.lookupvar```?

**Comment by stbenjam** [comment]
Yea, I'll change it, I did this before our discussion on the other PR.

**Comment by ekohl** [comment]
ACK

**Pull request merged**
