### PR TITLE
Use cache_data and random_password from extlib

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
I think it's going to cause issues that foreman's method is named the same, will they move to extlib?

**Comment by ehelms** [comment]
See https://github.com/theforeman/puppet-foreman/pull/364

**Comment by stbenjam** [comment]
Great :-)

We'll need puppet-foreman/foreman_proxy to update their versions so we can set the right requirements in metadata.json as well

**Comment by stbenjam** [comment]
APT, should go green when https://github.com/Katello/puppet-certs/pull/68 is merged

**Pull request merged**
