### PR TITLE
Fixes #14081 - disable repo auth to work around uber cert issue

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by mccun934** [comment]
ACK pending we get a followup issue filed to re-enable it

tested this and is just a reversal of https://github.com/Katello/puppet-katello/commit/27583c038b3d3f104533f18779c486fee83b912f

**Comment by jlsherrill** [comment]
Issued opened http://projects.theforeman.org/issues/14082

**Comment by mccun934** [comment]
:+1:

**Comment by ehelms** [comment]
Will you set the commit title to include `Fixes -` we are working on tieing this into Redmine auto-closing

**Comment by jlsherrill** [comment]
@ehelms updated

**Comment by ehelms** [comment]
ACK

**Pull request merged**
