### PR TITLE
Update katello.conf.erb

### PR DESCRIPTION
**Pull request by LincolnBryant**
Adding support for Scientific Linux

### CODE REVIEW

**Comment by ehelms** [comment]
@LincolnBryant do you think you will have time to tackle this or would you like one of the developers to take this over for you?

**Comment by LincolnBryant** [comment]
Unfortunately I am unable to commit time to this right now.

Feel free to take over the ticket, I am still interested in seeing Scientific Linux support added.

Cheers.

**Comment by ehelms** [comment]
Replacement PR -- https://github.com/Katello/puppet-katello/pull/69

**Comment by ehelms** [comment]
Closing now that #69 is in

**Pull request closed without merging**
